### ISSUE TITLE
On slower systems, Angular's vendor.js takes a long time to load

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#544]
Most of the centers don't have the fast internet that we do at home. Voz's connection for example is only 5Mbps on a good day. So they are getting results like this when trying to load V2:

![image](https://user-images.githubusercontent.com/3819970/62505239-a0b73880-b7b0-11e9-9929-1d3ffc9981b8.png)

What to do:

1. Check if AppVeyor is [building Angular6 in prod mode](https://stackoverflow.com/a/51257973/2496266)
2. See if we can remove any dependencies or move them to devDependencies in package.json

Other ideas welcome.

**Comment by jcii** [comment]
CDN

**Comment by chaim1221** [comment]
```
before_build:
  - sh: node --version
  - sh: dotnet --version
  - sh: dotnet clean
  - sh: cd UI
  - sh: npm install
  - sh: npm run --silent build-local-dev
  - sh: npm run start-local-dev &
  - sh: cd ..
  - sh: sed -i "s/APPVEYOR_VERSION/$APPVEYOR_BUILD_VERSION/" "./Machete.Web/Views/Home/Index.cshtml"
  - sh: dotnet build
```
Test and use the prod build, is probably the solution.
https://github.com/SavageLearning/Machete/blob/develop/appveyor.yml
